// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc/sample.proto
#ifndef GRPC_rpc_2fsample_2eproto__INCLUDED
#define GRPC_rpc_2fsample_2eproto__INCLUDED

#include "rpc/sample.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sample {

class Sample final {
 public:
  static constexpr char const* service_full_name() {
    return "sample.Sample";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Ask(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::sample::AskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>> AsyncAsk(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>>(AsyncAskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>> PrepareAsyncAsk(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>>(PrepareAsyncAskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Ask(::grpc::ClientContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ask(::grpc::ClientContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>* AsyncAskRaw(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sample::AskResponse>* PrepareAsyncAskRaw(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ask(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::sample::AskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>> AsyncAsk(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>>(AsyncAskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>> PrepareAsyncAsk(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>>(PrepareAsyncAskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ask(::grpc::ClientContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response, std::function<void(::grpc::Status)>) override;
      void Ask(::grpc::ClientContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>* AsyncAskRaw(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sample::AskResponse>* PrepareAsyncAskRaw(::grpc::ClientContext* context, const ::sample::AskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Ask(::grpc::ServerContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAsk(::grpc::ServerContext* context, ::sample::AskRequest* request, ::grpc::ServerAsyncResponseWriter< ::sample::AskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ask<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ask() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sample::AskRequest, ::sample::AskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::sample::AskRequest* request, ::sample::AskResponse* response) { return this->Ask(context, request, response); }));}
    void SetMessageAllocatorFor_Ask(
        ::grpc::MessageAllocator< ::sample::AskRequest, ::sample::AskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sample::AskRequest, ::sample::AskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ask(
      ::grpc::CallbackServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ask<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAsk(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ask() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ask(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sample::AskRequest, ::sample::AskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sample::AskRequest, ::sample::AskResponse>* streamer) {
                       return this->StreamedAsk(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ask(::grpc::ServerContext* /*context*/, const ::sample::AskRequest* /*request*/, ::sample::AskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAsk(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sample::AskRequest,::sample::AskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ask<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ask<Service > StreamedService;
};

}  // namespace sample


#endif  // GRPC_rpc_2fsample_2eproto__INCLUDED
